language: python
python:
  - 3.8
before_install:
  - pip install -U pip
install:
  - pip install coverage
  - pip install flake8
  - pip install coveralls
script:
  - coverage run -m unittest discover -s ./tests/
  - flake8 .
after_success:
  - coveralls
